#!bin/bash
user=$"userlin"
password=$"P@ssw0rd"
sudo curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt update -y &&
sudo apt install nodejs -y &&
useradd -m  "$user"
usermod -s /bin/bash "$user"
echo "$user:$password" | chpasswd
usermod -aG sudo $user
su - $user
echo "P@ssw0rd" | sudo mkdir ~/application

cd ~/application

sudo git clone https://github.com/ConnecttheCloud/nodejs-nginx.git >> /dev/null 2>&1 

cd */

npm install -y &&
node *.js

echo "y" | ufw enable
ufw allow ssh
ufw allow http
ufw allow https
ufw allow 3000
